### ISSUE TITLE
Import ERROR "from PySide.QtCore import *"

### ISSUE THREAD

**Issue by GelosSnake** [Vector35/binaryninja-python#6]
Not sure exactly whats the problem here, latest OSX:

$python binja.py 
Traceback (most recent call last):
  File "binja.py", line 25, in <module>
    import Threads
  File "/binaryninja-python/Threads.py", line 16, in <module>
    from PySide.QtCore import *
ImportError: dlopen(/Library/Python/2.7/site-packages/PySide/QtCore.so, 2): Library not loaded: libpyside-python2.7.1.2.dylib
  Referenced from: /Library/Python/2.7/site-packages/PySide/QtCore.so
  Reason: image not found

**Comment by psifertex** [comment]
Just to confirm you followed the installation instructions and installed both Qt and pyside? We should probably update our list, Qt with a version less than 5 is a pre-requisite for pyside, but we don't explicitly call it out, you have to read their install instructions.

**Comment by psifertex** [comment]
No response yet, going to mark this as closed -- feel free to comment and I'll re-open it if you find it's a bug after double checking the install process.
